#!/usr/bin/python3
"""Generates a .tgz archive from the contents of the web_static"""

from fabric.api import *
from time import strftime


def do_pack():
    time_format = strftime("%Y%m%d%H%M%S")
    try:
        local("mkdir -p versions")
        local("tar -czvf versions/web_static_{}.tgz web_static/"
              .format(time_format)
        return ("versions/web_static_{}.tgz"
                .format(time_format)
    except Exception:
        return None
